export default () => ({
  templatesList: [],
  newTemplatesList : [],
  totalItems: 0,
  templateDetails: {
    configuration: 'optimize_cars_then_locality_grouping',
    loading_end_time: null,
    loading_start_time: null,
    loading_time: null,
    offloading_end_time: null,
    offloading_start_time: null,
    offloading_time: null,
    planning_time: null,
    // result_ttl: null,
    template_name: null,
    round_trip: false,
    // disable_compatibility: false,
     disable_time_windows: false,
    toll_roads: true,
    trafic_jams: true,
    zone_constraint: false,
    fill_ratio: 100,
  },
  readOnly: false,
  editMode: false,
})
